services:
  media:
    image: bluenviron/mediamtx:latest
    network_mode: host
    volumes: [ ./media-service/mediamtx.yml:/mediamtx.yml:ro ]

  bridge:
    build: bridge
    network_mode: host
    volumes: [ ./store.db:/data/store.db ]
    depends_on: [ media ]

  web:
    build: web
    network_mode: host
    volumes: [ ./store.db:/store.db ]
    environment: [ JWT_SECRET=157758cf5b3b88f84fd82ab6ce481bb7883063bcd15eb35495729dc9deb2b1e7, DEVICE_KEY=register123, BASE_UDP=5001 ]
    depends_on: [ bridge ]
